# Generated by Django 5.1.3 on 2024-11-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='products',
            new_name='product',
        ),
    ]
