# Generated by Django 5.1.3 on 2024-11-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_products_wishlist_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='products',
        ),
    ]
