# Generated by Django 5.1.3 on 2024-11-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_product_wishlist_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='homepage.watchesuploads'),
        ),
    ]
