# Generated by Django 5.1.3 on 2024-11-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_cart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='products',
        ),
    ]
