# Generated by Django 5.1.3 on 2024-11-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_rename_product_cartitem_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
